### ISSUE TITLE
feature request: config file for default test duration

### ISSUE THREAD

**Issue by fennecdjay** [bloznelis/typioca#102]
first of thanks for this nice software.
turns out i prefer using 1 minute tests rather than the default 30 seconds, so i wondered if it would be possible to store that in a config file

**Comment by bloznelis** [comment]
Hey, that's a good idea. 

Probably can be extended to having not only test duration, but all configuration stored. Maybe best for UX would be if we persisted settings selected by the user in the main menu.

Thanks for the request @fennecdjay, will work on this in the near future.

**Comment by fennecdjay** [comment]
you're right configuration persistance would be awesome

**Comment by bloznelis** [comment]
This is added as part of [2.3.0](https://github.com/bloznelis/typioca/releases/tag/2.3.0), let me know if it suits your needs, @fennecdjay !

**Comment by fennecdjay** [comment]
It does :smiley:
Amazing how fast you were to include this.
Thanks a lot!
