### ISSUE TITLE
Touch Typing Tutorial 

### ISSUE THREAD

**Issue by dacyberduck** [bloznelis/typioca#146]
Any chance of adding touch typing tutorials like in KTouch?

**Comment by bloznelis** [comment]
That would be nice, but maybe as a separate project, reusing most of the internals (?). Just avoid feature creep here and keep this project minimal.

**Comment by dacyberduck** [comment]
Well

> That would be nice, but maybe as a separate project, reusing most of the internals (?). Just avoid feature creep here and keep this project minimal.

You can maybe add it as an optional feature with a dedicated Makeflag to enable or disable.
