### ISSUE TITLE
Query about v3.1.0

### ISSUE THREAD

**Issue by kskarthik** [bloznelis/typioca#168]
Is this a re release? I have packaged version some time ago

https://repology.org/project/typioca/versions

**Comment by bloznelis** [comment]
Sorry, what's the question?

**Comment by kskarthik** [comment]
> Sorry, what's the question?

I have packaged v3.1.0 some time ago. But when i see now,  

![Uploading image.png…]()

**Comment by kskarthik** [comment]
It's my mistake, please ignore
