### ISSUE TITLE
0 wpm

### ISSUE THREAD

**Issue by tripplehelix** [bloznelis/typioca#25]
![Screenshot_20220520_150958](https://user-images.githubusercontent.com/16861223/169546149-cb5b8666-8335-44c3-a86c-55403642dadf.png)
![Screenshot_20220520_151022](https://user-images.githubusercontent.com/16861223/169546153-f404cf34-b13f-48fb-858d-be6db29786a6.png)

Ummm... 0 wpm I don't think that's right.

**Comment by bloznelis** [comment]
Pushed a fix! @tripplehelix
