### ISSUE TITLE
[suggestion] typioca -v

### ISSUE THREAD

**Issue by tripplehelix** [bloznelis/typioca#28]
Would be nice to either show version number in the program or be able to run typioca -v

**Comment by bloznelis** [comment]
Thanks for the suggestion :clap:

**Comment by tripplehelix** [comment]
![image](https://user-images.githubusercontent.com/16861223/169690004-d39ec190-bba5-45b5-9d99-893d3f2e26fd.png)
...

**Comment by bloznelis** [comment]
Hmm, that is weird. Which OS are you running this on @tripplehelix ?

**Comment by tripplehelix** [comment]
![image](https://user-images.githubusercontent.com/16861223/169691729-07b1a444-107c-4fcd-948b-756a089b96f5.png)

**Comment by tripplehelix** [comment]
> 

I'm doing so by following the 'Building from source' guide. Then moving the typioca exec to my .local/bin/

**Comment by tripplehelix** [comment]
![image](https://user-images.githubusercontent.com/16861223/171475041-1504e930-239e-47a4-95ff-c45435f211ac.png)

I usually pull the exec out into .local/bin/
