### ISSUE TITLE
after the latest update can no longer start 'Timer run' and 'Sentence count run'.

### ISSUE THREAD

**Issue by diggajupadhyay** [bloznelis/typioca#30]
I had been running the app inside Docker just fine for few days and today when I tried to build new image with new update it would give me certain errors :( However, 'Word count run' works fine still. Please see the debug output below:

> Caught panic:
strings: negative Repeat count
Restoring terminal...
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.20.0/tea.go:359 +0x95
panic({0x6d2180, 0x7f2c80})
        /usr/local/go/src/runtime/panic.go:844 +0x258
strings.Repeat({0x7f1d30?, 0xc000204750?}, 0x1?)
        /usr/local/go/src/strings/strings.go:533 +0x4d8
github.com/muesli/reflow/indent.(*Writer).Write(0xc0002485f0, {0xc00012ccc8?, 0xb, 0xb?})
        /go/pkg/mod/github.com/muesli/reflow@v0.3.0/indent/indent.go:78 +0x172
github.com/muesli/reflow/indent.Bytes({0xc00012ccc8, 0xb, 0x20}, 0xffffffffffffffb2)
        /go/pkg/mod/github.com/muesli/reflow@v0.3.0/indent/indent.go:48 +0xa8
github.com/muesli/reflow/indent.String(...)
        /go/pkg/mod/github.com/muesli/reflow@v0.3.0/indent/indent.go:56
main.model.indent(...)
        /app/src/view.go:258
main.model.View({{0x7121a0, 0xc000264000}, {0xc00000e3a8, 0xc00000e3c0, 0xc00001a890, 0x79f318, 0xc00001a8a0, 0xc00001a8b0, 0xc00001a8c0, 0xc00001a8d0}, ...})
        /app/src/view.go:183 +0x182a
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc00011e300)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.20.0/tea.go:549 +0x1398
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.20.0/tea.go:556
main.glob..func1(0x9b7fc0?, {0x73030c?, 0x0?, 0x0?})
        /app/src/main.go:57 +0x22a
github.com/spf13/cobra.(*Command).execute(0x9b7fc0, {0xc000012230, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x9b7fc0)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /app/src/main.go:124 +0x25
bye!

**Comment by bloznelis** [comment]
Thanks, for reporting this. Might be related how we treat terminal dimensions now. This happens only when running inside docker, right?

**Comment by bloznelis** [comment]
Is this still an issue @diggajupadhyay ?

**Comment by diggajupadhyay** [comment]
@bloznelis thank you. it now builds and run perfectly.
