### ISSUE TITLE
Space handling

### ISSUE THREAD

**Issue by worekleszczy** [bloznelis/typioca#42]
Hi,

First of all thank you @bloznelis for creating this tool  - I really enjoy using `typioca` - ATM I'm trying to integrate it with my morning routine 🙃 

Getting back to business - I found a potential bug - when clicking space in the middle of the word it jumps ahead to the beginning of the next one marking all remaining characters as invalid. 

I'm using mac with zsh shell.

**Comment by bloznelis** [comment]
Hey, @worekleszczy, it's actually by design. The reasoning behind that is that if one messes up a word and don't want to even bother fixing it, he/she can jump to the next word instantly.

**Comment by bloznelis** [comment]
Once/If we introduce a persistent configuration, we can make this behavior configurable though!

**Comment by worekleszczy** [comment]
Ok, now I understand the reasoning behind it 🙂 

> Once/If we introduce a persistent configuration, we can make this behaviour configurable though!

That sounds great! - I'd personally move this behaviour to e.g TAB 🙃
