### ISSUE TITLE
Keyboard layouts emulation

### ISSUE THREAD

**Issue by bloznelis** [bloznelis/typioca#81]
Add Dvorak and Colemak layouts emulation (mapping from QWERTY)

**Comment by tripplehelix** [comment]
Just wondering here, couldn't you just change your system keyboard layout to achieve this?

**Comment by DanWlker** [comment]
Hi are you accepting any PRs for this? I'm interested to work on it

**Comment by bloznelis** [comment]
Go ahead @DanWlker. Just keep in mind that we need this to be configurable via the main menu, probably under a Config section. And the code that handles the menu is not the greatest with loads of duplication, so be warned!
